export const COVID_GET_STATE_DATA = 'COVID/STATE/GET_DATA';
export const COVID_GET_STATE_DATA_SUCCESS = 'COVID/STATE/GET_DATA_SUCCESS';
export const COVID_GET_STATE_DATA_FAILURE = 'COVID/STATE/GET_DATA_FAILURE';
export const COVID_GET_STATE_DATA_RESET = 'COVID/STATE/GET_DATA_RESET';
